
package ca.bcit.comp3656.a00742038.assignment1.xml;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EmployeeAccess", targetNamespace = "http://www.bcit.ca/comp3656/a00742038/assignment1/xml/", wsdlLocation = "http://localhost:8080/a00742038/EmployeeAccess?wsdl")
public class EmployeeAccess
    extends Service
{

    private final static URL EMPLOYEEACCESS_WSDL_LOCATION;
    private final static WebServiceException EMPLOYEEACCESS_EXCEPTION;
    private final static QName EMPLOYEEACCESS_QNAME = new QName("http://www.bcit.ca/comp3656/a00742038/assignment1/xml/", "EmployeeAccess");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/a00742038/EmployeeAccess?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPLOYEEACCESS_WSDL_LOCATION = url;
        EMPLOYEEACCESS_EXCEPTION = e;
    }

    public EmployeeAccess() {
        super(__getWsdlLocation(), EMPLOYEEACCESS_QNAME);
    }

    public EmployeeAccess(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPLOYEEACCESS_QNAME, features);
    }

    public EmployeeAccess(URL wsdlLocation) {
        super(wsdlLocation, EMPLOYEEACCESS_QNAME);
    }

    public EmployeeAccess(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPLOYEEACCESS_QNAME, features);
    }

    public EmployeeAccess(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeeAccess(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmployeeServicesPortAPI
     */
    @WebEndpoint(name = "EmployeeServicesPortAPI")
    public EmployeeServicesPortAPI getEmployeeServicesPortAPI() {
        return super.getPort(new QName("http://www.bcit.ca/comp3656/a00742038/assignment1/xml/", "EmployeeServicesPortAPI"), EmployeeServicesPortAPI.class);
    }

    /**
     * 
     * @param features
     *     A list of {&#064;link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the &lt;code&gt;features&lt;/code&gt; parameter will have their default values.
     * @return
     *     returns EmployeeServicesPortAPI
     */
    @WebEndpoint(name = "EmployeeServicesPortAPI")
    public EmployeeServicesPortAPI getEmployeeServicesPortAPI(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.bcit.ca/comp3656/a00742038/assignment1/xml/", "EmployeeServicesPortAPI"), EmployeeServicesPortAPI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPLOYEEACCESS_EXCEPTION!= null) {
            throw EMPLOYEEACCESS_EXCEPTION;
        }
        return EMPLOYEEACCESS_WSDL_LOCATION;
    }

}
