
package ca.bcit.comp3656.a00742038.assignment1.jaxws.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EmployeeAccessService", targetNamespace = "http://service.jaxws.assignment1.a00742038.comp3656.bcit.ca/", wsdlLocation = "http://localhost:8080/a00742038/EmployeeAccess?wsdl")
public class EmployeeAccessService
    extends Service
{

    private final static URL EMPLOYEEACCESSSERVICE_WSDL_LOCATION;
    private final static WebServiceException EMPLOYEEACCESSSERVICE_EXCEPTION;
    private final static QName EMPLOYEEACCESSSERVICE_QNAME = new QName("http://service.jaxws.assignment1.a00742038.comp3656.bcit.ca/", "EmployeeAccessService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/a00742038/EmployeeAccess?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPLOYEEACCESSSERVICE_WSDL_LOCATION = url;
        EMPLOYEEACCESSSERVICE_EXCEPTION = e;
    }

    public EmployeeAccessService() {
        super(__getWsdlLocation(), EMPLOYEEACCESSSERVICE_QNAME);
    }

    public EmployeeAccessService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPLOYEEACCESSSERVICE_QNAME, features);
    }

    public EmployeeAccessService(URL wsdlLocation) {
        super(wsdlLocation, EMPLOYEEACCESSSERVICE_QNAME);
    }

    public EmployeeAccessService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPLOYEEACCESSSERVICE_QNAME, features);
    }

    public EmployeeAccessService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeeAccessService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmployeeServicesPortAPI
     */
    @WebEndpoint(name = "EmployeeAccessPort")
    public EmployeeServicesPortAPI getEmployeeAccessPort() {
        return super.getPort(new QName("http://service.jaxws.assignment1.a00742038.comp3656.bcit.ca/", "EmployeeAccessPort"), EmployeeServicesPortAPI.class);
    }

    /**
     * 
     * @param features
     *     A list of {&#064;link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the &lt;code&gt;features&lt;/code&gt; parameter will have their default values.
     * @return
     *     returns EmployeeServicesPortAPI
     */
    @WebEndpoint(name = "EmployeeAccessPort")
    public EmployeeServicesPortAPI getEmployeeAccessPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.jaxws.assignment1.a00742038.comp3656.bcit.ca/", "EmployeeAccessPort"), EmployeeServicesPortAPI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPLOYEEACCESSSERVICE_EXCEPTION!= null) {
            throw EMPLOYEEACCESSSERVICE_EXCEPTION;
        }
        return EMPLOYEEACCESSSERVICE_WSDL_LOCATION;
    }

}
