
package ca.bcit.comp3656.a00742038.assignment1.jaxws.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import ca.bcit.comp3656.a00742038.assignment1.types.AddEmployeeRequest;
import ca.bcit.comp3656.a00742038.assignment1.types.AddEmployeeResponse;
import ca.bcit.comp3656.a00742038.assignment1.types.DeleteEmployeeRequest;
import ca.bcit.comp3656.a00742038.assignment1.types.DeleteEmployeeResponse;
import ca.bcit.comp3656.a00742038.assignment1.types.FindEmployeeRequest;
import ca.bcit.comp3656.a00742038.assignment1.types.FindEmployeeResponse;
import ca.bcit.comp3656.a00742038.assignment1.types.ListEmployeeResponse;
import ca.bcit.comp3656.a00742038.assignment1.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeServicesPortAPI", targetNamespace = "http://www.bcit.ca/comp3656/a00742038/assignment1/xml/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeServicesPortAPI {


    /**
     * 
     * @param findEmpReq
     * @return
     *     returns ca.bcit.comp3656.a00742038.assignment1.types.FindEmployeeResponse
     * @throws FindError
     */
    @WebMethod
    @WebResult(name = "findEmployeeResponse", targetNamespace = "http://www.bcit.ca/comp3656/a00742038/assignment1/types/", partName = "findEmpRes")
    public FindEmployeeResponse findEmployee(
        @WebParam(name = "findEmployeeRequest", targetNamespace = "http://www.bcit.ca/comp3656/a00742038/assignment1/types/", partName = "findEmpReq")
        FindEmployeeRequest findEmpReq)
        throws FindError
    ;

    /**
     * 
     * @param addReq
     * @return
     *     returns ca.bcit.comp3656.a00742038.assignment1.types.AddEmployeeResponse
     * @throws AddError
     */
    @WebMethod
    @WebResult(name = "addEmployeeResponse", targetNamespace = "http://www.bcit.ca/comp3656/a00742038/assignment1/types/", partName = "addRes")
    public AddEmployeeResponse add(
        @WebParam(name = "addEmployeeRequest", targetNamespace = "http://www.bcit.ca/comp3656/a00742038/assignment1/types/", partName = "addReq")
        AddEmployeeRequest addReq)
        throws AddError
    ;

    /**
     * 
     * @return
     *     returns ca.bcit.comp3656.a00742038.assignment1.types.ListEmployeeResponse
     * @throws ListError
     */
    @WebMethod
    @WebResult(name = "listEmployeeResponse", targetNamespace = "http://www.bcit.ca/comp3656/a00742038/assignment1/types/", partName = "listRes")
    public ListEmployeeResponse listEmployees()
        throws ListError
    ;

    /**
     * 
     * @param deleteReq
     * @return
     *     returns ca.bcit.comp3656.a00742038.assignment1.types.DeleteEmployeeResponse
     * @throws DeleteError
     */
    @WebMethod
    @WebResult(name = "deleteEmployeeResponse", targetNamespace = "http://www.bcit.ca/comp3656/a00742038/assignment1/types/", partName = "deleteRes")
    public DeleteEmployeeResponse delete(
        @WebParam(name = "deleteEmployeeRequest", targetNamespace = "http://www.bcit.ca/comp3656/a00742038/assignment1/types/", partName = "deleteReq")
        DeleteEmployeeRequest deleteReq)
        throws DeleteError
    ;

}
